--- 
- 
  hosts: all
  remote_user: uipath
  tasks:
  - name: apt-get update 
    apt: 
      update_cache: yes
    become: yes
    become_method: sudo
  - name: apt-get upgrade 
    apt: 
      name: '*'
      state: latest
    become: yes
    become_method: sudo
  - import_tasks: 'node-red/node-red.yml'
#  - import_tasks: 'stanford-nlp/stanford.yml'